Repository spacetelescope/rad, pull requests merged in 2024-02, with the labels that each got.

#367 Fix devdeps
  README.md
  tox.ini
Labels: no-changelog-entry-needed, Weekly CI

#372 update metadata for release `0.19.0`
  CHANGES.rst
Labels: no-changelog-entry-needed

#379 Ref links
  docs/conf.py
Labels: documentation, no-changelog-entry-needed

#386 RAD-154: Improve documentation
  CHANGES.rst
  docs/index.rst
  docs/reference_files.rst
  docs/schemas.rst
Labels: documentation
